In [18]:
import pandas as pd
import numpy as np
import pandas_profiling as pp

In [ ]:
df.drop("Cabin",axis=1,inplace=True)
df

In [31]:
df.Age.fillna(df.Age.mean(skipna=True),inplace=True)
df.Embarked.fillna("S",inplace=True)

In [1]:
df.columns

NameError: name 'df' is not defined

In [32]:
X = df.drop(["Survived","Name","Ticket"],axis=1)
X.Sex.replace({"male":0,"female":1},inplace=True)
X.Embarked.replace({"S":1,"C":2,"Q":3},inplace=True)
X = X.values
y = df.Survived.values

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
logt = LogisticRegression(random_state=0)
logt.fit(X_train,y_train)
y_pred = logt.predict(X_test)
score =accuracy_score(y_test,y_pred)
cn = confusion_matrix(y_test,y_pred)
print (cn)
print (score)

[[90 15]
 [20 54]]
0.8044692737430168


C:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
ranfort = RandomForestClassifier(random_state=0)
ranfort.fit(X_train,y_train)
y_pred1 = ranfort.predict(X_test)
score1 =accuracy_score(y_test,y_pred1)
cn1 = confusion_matrix(y_test,y_pred1)
print (cn1)
print (score1)

[[91 14]
 [19 55]]
0.8156424581005587


C:\Users\hp\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [36]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
dectree = DecisionTreeClassifier(random_state=0)
dectree.fit(X_train,y_train)
y_pred2 = dectree.predict(X_test)
score2 =accuracy_score(y_test,y_pred2)
cn2 = confusion_matrix(y_test,y_pred2)
print (cn2)
print (score2)

[[88 17]
 [21 53]]
0.7877094972067039


In [78]:
df2 = pd.read_csv("test.csv",index_col=0)
df2.Age.fillna(df2.Age.mean(skipna=True),inplace=True)
df2.drop(["Name","Ticket","Cabin"],axis=1 ,inplace=True)
df2.Embarked.fillna("S")
df2.Sex.replace({"male":0,"female":1},inplace=True)
df2.Embarked.replace({"S":1,"C":2,"Q":3},inplace=True)
df2.Fare.fillna(df2.Fare.mean(skipna=True),inplace=True)
X1_test = df2.values
prediction = ranfort.predict(X1_test)
df3 = pd.DataFrame({"PassengerID":df2.index,"Survived":prediction})
print(df3)

     PassengerID  Survived
0            892         0
1            893         0
2            894         0
3            895         1
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]
